# Generated by Django 5.2.4 on 2025-08-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Превью'),
        ),
    ]
